ADA compliance
Xtendify/Simple-Calendar pull request #320
Opened 2019-03-19 12:00 UTC by syntax53

There are issues with the NAV buttons and satisfying ADA compliance for web sites -- http://wave.webaim.org .  These changes satisfy the checker.

2023-01-27 08:42 UTC, rosinghal commented
@syntax53 would you be open to check if it works with the latest WP and PHP since this is a very old PR?

2023-01-27 08:44 UTC, rosinghal requested changes

2023-01-27 08:44 UTC, rosinghal commented on includes/calendars/views/default-calendar-grid.php
> +							<td class="simcal-nav simcal-prev-wrapper" colspan="<?php echo apply_filters( 'simcal_prev_cols', '1' ); ?>">
Interested to know why this changed from `th` to `td`?

2023-01-27 08:44 UTC, rosinghal commented on includes/calendars/views/default-calendar-grid.php
> +								<button class="simcal-nav-button simcal-month-nav simcal-prev" title="<?php _e( 'Previous Month', 'google-calendar-events' ); ?>"><i class="simcal-icon-left"></i><span style="display:none;"><
Can we use `ARIA` instead of adding a hidden text?

2023-01-27 08:44 UTC, rosinghal commented on includes/calendars/views/default-calendar-list.php
> +				echo "\t\t\t" . '<span style="display:none;">' . __('Previous', 'google-calendar-events') . '</span>' . "\n";
Same here, can we can use `ARIA` in the above line?

2025-09-17 07:54 UTC, closed without merging

2025-09-17 08:02 UTC, Akhill2020 commented
There is no reply in the PR so closing it.